<?php
return array(
    'forename' => array(
        'title' => 'First name',
        'required' => true,
        'type' => 'text',
        'description' => 'Required',
    ),
    'surname' => array(
        'title' => 'Last name',
        'required' => true,
        'type' => 'text',
        'description' => 'Required',
    ),
    'email' => array(
        'title' => 'Email',
        'required' => true,
        'type' => 'text',
        'description' => 'Required',
    ),
    'salutation' => array(
        'title' => 'Salutation',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'telephone' => array(
        'title' => 'Phone',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'gsm' => array(
        'title' => 'Mobile',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'website' => array(
        'title' => 'Website',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'country' => array(
        'title' => 'Country',
        'required' => false,
        'type' => 'text',
        'description' => 'country code according to ISO 3166-1 alpha-2. For Belgium: "BE"',
    ),
    'zipcode' => array(
        'title' => 'Zip Code',
        'required' => false,
        'type' => 'number',
        'description' => '',
    ),
    'city' => array(
        'title' => 'City',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'street' => array(
        'title' => 'Street',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'number' => array(
        'title' => 'Number',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'address_name_delivery' => array(
        'title' => 'Delivery Address',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'zipcode_delivery' => array(
        'title' => 'Delivery Zip Code',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'city_delivery' => array(
        'title' => 'Delivery City',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'street_delivery' => array(
        'title' => 'Delivery Street',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'number_delivery' => array(
        'title' => 'Delivery Number',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'address_name_visiting' => array(
        'title' => 'Visiting Address',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'zipcode_visiting' => array(
        'title' => 'Visiting Zip Code',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'city_visiting' => array(
        'title' => 'Visiting City',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'street_visiting' => array(
        'title' => 'Visiting Street',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'number_visiting' => array(
        'title' => 'Visiting Number',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'address_name_invoicing' => array(
        'title' => 'Invoicing Address',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'zipcode_invoicing' => array(
        'title' => 'Invoicing Zip Code',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'city_invoicing' => array(
        'title' => 'Invoicing City',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'street_invoicing' => array(
        'title' => 'Invoicing Street',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'number_invoicing' => array(
        'title' => 'Invoicing Number',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'invoice_email_address' => array(
        'title' => 'Invoice Email',
        'required' => false,
        'type' => 'text',
        'description' => '',
    ),
    'language' => array(
        'title' => 'Language',
        'required' => false,
        'type' => 'text',
        'description' => 'language code according to ISO 639-1. For Dutch: "NL"',
    ),
    'gender' => array(
        'title' => 'Gender',
        'required' => false,
        'type' => 'text',
        'description' => 'M/F/U',
    ),
    'dob' => array(
        'title' => 'Date Of Birth',
        'required' => false,
        'type' => 'text',
        'description' => 'unix timestamp',
    ),
    'description' => array(
        'title' => 'Description',
        'required' => false,
        'type' => 'textarea',
        'description' => 'background information on the contact',
    ),
    'newsletter' => array(
        'title' => 'Newsletter',
        'required' => false,
        'type' => 'boolean',
        'description' => '',
    ),
    'add_tag_by_string' => array(
        'title' => 'Add tag by string',
        'required' => false,
        'type' => 'text',
        'description' => 'pass one or more tags, comma-separated. Existing tags will be reused, other tags will be automatically created for you.',
    ),
    'automerge_by_name' => array(
        'title' => 'Auto merge by name',
        'required' => false,
        'type' => 'boolean',
        'description' => 'If this flag is set to 1, Teamleader will merge this info into an existing contact with the same forename and surname, if it finds any. Default: 0',
    ),
    'automerge_by_email' => array(
        'title' => 'Auto merge by email',
        'required' => false,
        'type' => 'boolean',
        'description' => 'If this flag is set to 1, Teamleader will merge this info into an existing contact with the same email address, if it finds any.',
    ),
    'tracking' => array(
        'title' => 'Tracking',
        'required' => false,
        'type' => 'text',
        'description' => 'title of the activity',
    ),
    'tracking_long' => array(
        'title' => 'Tracking Long',
        'required' => false,
        'type' => 'text',
        'description' => 'description of the activity',
    ),
);